# Generated by Django 4.0.4 on 2022-06-21 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(max_length=50)),
                ('home_goals', models.IntegerField()),
                ('home_conceded', models.IntegerField()),
                ('home_league_avg', models.IntegerField()),
                ('away_name', models.CharField(max_length=50)),
                ('away_goals', models.IntegerField()),
                ('away_conceded', models.IntegerField()),
                ('away_league_avg', models.IntegerField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
