# Generated by Django 4.0.4 on 2022-06-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_parameter_away_results_parameter_home_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='over_three',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='over_two',
            field=models.FloatField(null=True),
        ),
    ]
