# Generated by Django 4.0.4 on 2022-06-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_parameter_over_three_parameter_over_two'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='parameter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
