# Generated by Django 4.0.4 on 2022-06-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_parameter_options_parameter_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='away_resultsint',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='home_resulsint',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='overthreeint',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='overtwoint',
            field=models.FloatField(null=True),
        ),
    ]
