# Generated by Django 4.0.4 on 2022-06-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_parameter_away_resultsint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='away_resultsint',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='home_resulsint',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='overthreeint',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='overtwoint',
            field=models.FloatField(null=True),
        ),
    ]
