# Generated by Django 4.0.4 on 2022-06-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_parameter_away_resultsint_parameter_home_resulsint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='away_resultsint',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='home_resulsint',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='overthreeint',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='overtwoint',
        ),
    ]
